### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by wowbagger84** [telldus/tellstick-lua-examples#3]
Is it possible to have some sort of list of available basic commands? Like some documentation. This is the only place I found for making tellstick to custom things, but can they be triggered like commands from the rest of the system? can they keep running in the background? Can you catch incoming signals? Would also like a step by step guide for getting started.

**Comment by mickeprag** [comment]
Documentation is available here:
https://tellstick-server.readthedocs.io/en/latest/
Feel free to help out improving it.
